# Generated by Django 2.0.4 on 2018-06-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=255)),
                ('url_key', models.CharField(max_length=100)),
                ('article_writer', models.CharField(max_length=100)),
                ('music_writer', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
    ]
